In [1]:
import numpy as np
a=np.array([[10,20],[30,40]])
a

array([[10, 20],
       [30, 40]])

In [8]:
a=np.array([[10,20],[30,40]])
b=np.square(a)
b

array([[ 100,  400],
       [ 900, 1600]])

In [19]:
a=np.array([[10,20],[30,40]])
b= 100+a
b

array([[110, 120],
       [130, 140]])

In [15]:
a=np.array([[10,20],[30,40]])
b=5
a * b

array([[ 50, 100],
       [150, 200]])

In [21]:
a=np.array([[10,20],[30,40]])
b=np.sqrt(b)
print(np.sqrt(a))

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


In [33]:
array1=np.arange(3,28,3)
array1.resize(3,3)
array1

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [36]:
array2=np.linspace(10,20,9)
array2.resize(3,3)
array2

array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [37]:
array1*array2

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

In [42]:
!pip install numpy
!Install pandas and matplotlib to work on a sample example
!pip install pandas
!pip install matplotlib

usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...


In [5]:
import pandas as pd
df=pd.read_npy('process1.npy')
df.head(5)

AttributeError: module 'pandas' has no attribute 'read_npy'

In [19]:
import numpy as np
data1=np.load('process1.npy')
data1

array([[52, 12, 81,  0, 58]], dtype=int32)

In [20]:
data2=np.load('process2.npy')
data2

array([[96,  4, 61, 16, 43]], dtype=int32)

In [21]:
data3=np.load('process3.npy')
data3

array([[38, 96, 45, 17, 58]], dtype=int32)

In [22]:
data4=np.load('process4.npy')
data4

array([[97, 21, 22, 25,  6]], dtype=int32)

In [23]:
data5=np.load('process5.npy')
data5

array([[77,  6, 19,  2, 74]], dtype=int32)

In [29]:
n4=np.vstack((data1,data2,data3,data4,data5))
n4

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]], dtype=int32)

In [34]:
n5=n4.mean(axis=0)
n5

array([72. , 27.8, 45.6, 12. , 47.8])

# Numpy Project 1
## Ashley Ridley
## Version 1
## Fall semester 2023